---
- name: 'Setup Epel Repository'
  yum:
    name: http://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ release }}.noarch.rpm
    state: present

- name: 'Setup Puppet 3 Repository'
  yum:
    name: http://yum.puppetlabs.com/puppetlabs-release-el-{{ release }}.noarch.rpm
    state: present
  when: foreman_puppet_version is undefined or foreman_puppet_version == 3

- name: 'Setup Puppet 4 Repository'
  yum:
    name: https://yum.puppetlabs.com/puppetlabs-release-pc1-el-{{ release }}.noarch.rpm
    state: present
  when: foreman_puppet_version is defined and foreman_puppet_version == 4

- name: 'Setup Foreman Repository'
  yum:
    name: http://yum.theforeman.org/{{ "releases/" if foreman_version != 'nightly' else '' }}{{ foreman_version }}/el{{ release }}/x86_64/foreman-release.rpm
    state: present
