shells:
  install_shell: &install_shell
    shell: 'yum -y install ruby && cd /vagrant && ./setup.rb'
  bats_shell: &bats_shell
    shell: '/vagrant/bats/bootstrap_vagrant.sh'
  runcible_shell: &runcible_shell
    shell: '/vagrant/shells/runcible.sh'

boxes:
  centos6:
    box_name:   'centos/6'
    image_name: !ruby/regexp '/CentOS 6.*PV/'
    default:    true
    pty:        true

  centos7:
    box_name:   'centos/7'
    image_name: !ruby/regexp '/CentOS 7.*PV/'
    default:    true
    pty:        true

  centos7-atomic:
    box_name: centos7-atomic
    pty: true
    libvirt: http://cloud.centos.org/centos/7/atomic/images/CentOS-Atomic-Host-7-Vagrant-Libvirt.box

  centos6-foreman-nightly:
    box: centos6
    <<: *install_shell
    options: --scenario=foreman

  centos7-foreman-nightly:
    box: centos7
    <<: *install_shell
    options: --scenario=foreman

  centos6-katello-nightly:
    box: centos6
    <<: *install_shell
    options: --scenario=katello

  centos6-katello-p4-nightly:
    box: centos6
    ansible:
      playbook: 'playbooks/katello_nightly.yml'
      group: 'server'
      variables:
        common_puppet_version: 4

  centos6-capsule-nightly:
    box: centos6
    ansible:
      playbook: 'playbooks/capsule.yml'
      group: 'capsule'
      server: 'centos6-katello-nightly'

  centos6-capsule-p4-nightly:
    box: centos6
    ansible:
      playbook: 'playbooks/capsule.yml'
      group: 'capsule'
      server: 'centos6-katello-p4-nightly'
      variables:
        common_puppet_version: 4

  centos7-katello-nightly:
    box: centos7
    <<: *install_shell
    options: --scenario=katello --disable-selinux
    ansible:
      group: 'server'

  centos7-katello-p4-nightly:
    box: centos7
    ansible:
      playbook: 'playbooks/katello_nightly.yml'
      group: 'server'
      variables:
        common_puppet_version: 4

  centos7-capsule-nightly:
    box: centos7
    ansible:
      playbook: 'playbooks/capsule.yml'
      group: 'capsule'
      server: 'centos7-katello-nightly'

  centos7-capsule-p4-nightly:
    box: centos7
    ansible:
      playbook: 'playbooks/capsule.yml'
      group: 'capsule'
      server: 'centos7-katello-p4-nightly'
      variables:
        common_puppet_version: 4

  centos6-bats:
    box: centos6
    <<: *bats_shell

  centos7-bats:
    box: centos7
    <<: *bats_shell

  runcible:
    box: centos7
    <<: *runcible_shell
    privileged: false

  pipeline-katello-centos7:
    box: centos7
    memory: 4680

  pipeline-capsule-centos7:
    box: centos7
    memory: 3072

  pipeline-katello-3.1-centos7:
    box: centos7
    memory: 4680

  pipeline-capsule-3.1-centos7:
    box: centos7
    memory: 3072

  hammer-devel-centos7:
    box: centos7
    memory: 512
    ansible:
      playbook: 'playbooks/hammer_devel.yml'
      group: 'hammer_devel'
