---
- hosts: server capsule
  become: true
  vars:
    capsule_server_group: "server-{{ inventory_hostname }}"
    capsule_server: "{{ groups[capsule_server_group][0] }}"
  roles:
    - common
    - etc_hosts
    - capsule
